// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iomtslbibkblpcnegvbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvbXRzbGJpYmtibHBjbmVndmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDQxNTAsImV4cCI6MjA3MjQ4MDE1MH0.6HV5bZqZF8pAMWMCKAsXrdx_67dcxTKH2WrfDw_i_oY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});